export default [
  {
    id: 1,
    user_id: 4,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 2,
    user_id: 3,
    course_selection: 'MATH_1111',
    course_name: 'Math 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 3,
    user_id: 2,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 4,
    user_id: 4,
    course_selection: 'SOCI_1234',
    course_name: 'Sociology 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 5,
    user_id: 1,
    course_selection: 'MATH_1112',
    course_name: 'Geometry',
    semester: 'Summer',
    semester_fee: 123,
  },
  {
    id: 6,
    user_id: 1,
    course_selection: 'LANG_2014',
    course_name: 'Composition 2',
    semester: 'Summer',
    semester_fee: 123,
  },
  {
    id: 7,
    user_id: 2,
    course_selection: 'LANG_2014',
    course_name: 'Composition 2',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 8,
    user_id: 3,
    course_selection: 'LANG_2014',
    course_name: 'Composition 2',
    semester: 'Fall',
    semester_fee: 123,
  },
  {
    id: 9,
    user_id: 4,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 10,
    user_id: 4,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 11,
    user_id: 4,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 12,
    user_id: 3,
    course_selection: 'MATH_1111',
    course_name: 'Math 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 13,
    user_id: 2,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 14,
    user_id: 4,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 15,
    user_id: 1,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 16,
    user_id: 1,
    course_selection: 'LANG_2014',
    course_name: 'French',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 17,
    user_id: 2,
    course_selection: 'LANG_2014',
    course_name: 'French',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 18,
    user_id: 3,
    course_selection: 'MATH_1112',
    course_name: 'Math 2',
    semester: 'Winter Mini',
    semester_fee: 123,
  },
  {
    id: 19,
    user_id: 4,
    course_selection: 'LANG_2190',
    course_name: 'Language Arts 1',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 20,
    user_id: 4,
    course_selection: 'LANG_2191',
    course_name: 'Language Arts 2',
    semester: 'Summer',
    semester_fee: 123,
  },
  {
    id: 21,
    user_id: 1,
    course_selection: 'LANG_2012',
    course_name: 'Composition 2',
    semester: 'Spring',
    semester_fee: 123,
  },
  {
    id: 22,
    user_id: 1,
    course_selection: 'LANG_2012',
    course_name: 'Composition 2',
    semester: 'Winter',
    semester_fee: 123,
  },
  {
    id: 23,
    user_id: 1,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Winter',
    semester_fee: 123,
  },
  {
    id: 24,
    user_id: 1,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Fall',
    semester_fee: 123,
  },
  {
    id: 25,
    user_id: 1,
    course_selection: 'LANG_2012',
    course_name: 'Composition 1',
    semester: 'Fall',
    semester_fee: 123,
  },
];
